services:
  scrapper:
    image: ghcr.io/kiinami/vfd:latest
    container_name: vfd-scrapper
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      - "4242:4242"
    env_file: ./.env
