services:
  scrapper:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: vfd-scrapper
    restart: unless-stopped
    volumes:
      - ../data:/app/data
    env_file: ./.env
